@startuml
'https://plantuml.com/sequence-diagram

autonumber
 actor User
 box Application
    participant "Spring Security"
    participant "Spring Framework\nDispatcher Servlet"
 end box

User -> "Spring Security": <b>GET http://localhost:8080/hello.html

@enduml