app.services.greeting.message: Hello!
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

#  security:
#    user:
#      name: admin
#      password: admin
